### ISSUE TITLE
Plugin throwing exception on Android

### ISSUE THREAD

**Issue by triztian** [greenbits/datadog_flutter#2]
I've installed the plugin and see it successfully working on iOS, however in Android it is crashing, I'm initializing the logger like so:

```dart
const datadogClientToken = "s3cr37";

ddLogger = DatadogFlutter(
    clientToken: datadogClientToken,
    serviceName: 'flutter-clientapp',
    environment: 'production',
  );

ddLogger.log("DDLogging Initialized", Level.INFO);
```

When I call the `log` method I see the following exception trace:

```
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): Failed to handle method call
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): kotlin.KotlinNullPointerException
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at com.greenbits.datadog_flutter.DatadogFlutterPlugin.onMethodCall(DatadogFlutterPlugin.kt:83)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.greenbits.com/datadog_flutter(22883): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (22883): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, null, null, kotlin.KotlinNullPointerException
E/flutter (22883): 	at com.greenbits.datadog_flutter.DatadogFlutterPlugin.onMethodCall(DatadogFlutterPlugin.kt:83)
E/flutter (22883): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (22883): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (22883): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (22883): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (22883): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (22883): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (22883): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/flutter (22883): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22883): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter (22883): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (22883): )
E/flutter (22883): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (22883): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (22883): <asynchronous suspension>
E/flutter (22883): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (22883): #3      DatadogFlutter.log (package:datadog_flutter/datadog_flutter.dart:61:27)
E/flutter (22883): #4      main (package:client_app/main.dart:73:12)
E/flutter (22883): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (22883): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (22883): #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (22883): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (22883): #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (22883): #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (22883): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (22883): #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (22883): #13     Firebase.initializeApp (package:firebase_core/src/firebase.dart)
E/flutter (22883): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (22883): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (22883): #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (22883): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (22883): #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (22883): #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (22883): #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (22883): #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (22883): #22     MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart)
E/flutter (22883): #23     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (22883): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (22883): #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (22883): #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (22883): #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (22883): #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (22883): #29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (22883): #30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (22883): #31     MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart)
E/flutter (22883): #32     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (22883): #33     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (22883): #34     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (22883): #35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (22883): #36     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (22883): #37     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (22883): #38     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (22883): #39     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (22883): #40     Meth
```

**Comment by triztian** [comment]
I've submitted a [pull request](https://github.com/greenbits/datadog_flutter/pull/3) that fixes this issue in the plugin. But to address this in the flutter code I've created the following overriding class:

```dart
import 'package:logging/logging.dart';
import "package:datadog_flutter/datadog_flutter.dart";

class PDatadogFlutter extends DatadogFlutter {
  PDatadogFlutter({
    String clientToken,
    String serviceName,
    String loggerName,
    bool bindOnRecord = true,
    String environment = 'development',
  }) :  super(
      clientToken: clientToken,
      serviceName: serviceName,
      loggerName: loggerName,
      bindOnRecord: bindOnRecord,
      environment: environment
  );

  @override
  Future<void> log(String logMessage, Level logLevel,
      {Map<String, dynamic> attributes}) async {
    if (attributes == null) {
      return super.log(logMessage, logLevel, attributes: {}); //providing an empty prevents the exception
    }

    return super.log(logMessage, logLevel, attributes: attributes);
  }
}
```

You can then replace the `DatadogLogger` type with this one to handle the case when `attributes` argument is `null`.

```dart
DatadogFlutter ddLogger = PDatadogFlutter(
   clientToken: 's3cr37',
   serviceName: 'myapp',
   environment: 'development'
);
```

The "P" stands for "patched". Hope it helps someone!

**Comment by tshedor** [comment]
@triztian reading your PR, the Flutter code should **not** be necessary to include, right?

**Comment by triztian** [comment]
@tshedor you are correct it is not needed, the flutter code is just my workaround until the PR was accepted or a different change addressed the issue. Without having to change the plugin to build locally with any modifications.

**Comment by tshedor** [comment]
@triztian super. I'm going to close this issue then since #3 has been merged and released on pub dev. Thanks again for the contribution
