### ISSUE TITLE
Runtime Exception: Method call failed while Initialization

### ISSUE THREAD

**Issue by ashok2004** [greenbits/datadog_flutter#21]
`final ddLogger = DatadogLogger(loggerName: 'xyz');
`
Service Name is missing 

 ```
**call.method == "loggerCreateLogger" -> {
        val builder = Logger.Builder()
                .setNetworkInfoEnabled(true)
 104:               .setServiceName(call.argument<String>("serviceName")!!)**
```

Stack Trace:
```
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589): Failed to handle method call
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589): kotlin.KotlinNullPointerException
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at com.greenbits.datadog_flutter.DatadogFlutterPlugin.onMethodCall(DatadogFlutterPlugin.kt:104)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.greenbits.com/datadog_flutter( 6589):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

@tshedor  i think we are missing serviceName argument for this call.argument<String>("serviceName")!!

**Comment by ashok2004** [comment]
Fixed in commit https://github.com/greenbits/datadog_flutter/pull/23/commits/9e14689f1b82ea2b87f0a55c1f1dab42e24ba8f9
