### ISSUE TITLE
Web not supported 

### ISSUE THREAD

**Issue by acherifi** [greenbits/datadog_flutter#27]
Hi, 

I just tried to installed your plugin (which looks amazin BTW !) but i'm trying to vuild for web. 
By looking at the code it seems like your dart code directly calls the IOS and Android functions. 

As a result, the following error happens when I start the app 

```bash
Error: MissingPluginException(No implementation found for method initWithClientToken on channel
plugins.greenbits.com/datadog_flutter)
    at Object.throw_ [as throw] (http://localhost:33397/dart_sdk.js:5333:11)
    at MethodChannel._invokeMethod
    (http://localhost:33397/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:33397/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:33397/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:33397/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:33397/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:33397/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:33397/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:33397/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:33397/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:33397/dart_sdk.js:39181:13)
    at http://localhost:33397/dart_sdk.js:34688:9
```

Do you plan to support Web in the near future ?

**Comment by tshedor** [comment]
Hey @acherifi there aren't any near-future intentions to support Flutter web. I'm personally unfamiliar with how Flutter web's package system works. Are NPM/yarn importable? Can CDN assets be used? How can JS methods be invoked within Dart? 

I presently don't have an application that uses Web. But I'd really appreciate a PR if you have the time and courage to dive into Datadog's web SDK. It's definitely more thorough w/r/t RUM and out-of-the-box features.

**Comment by tshedor** [comment]
Hey @acherifi I've decided to try out Flutter web. Would you be so kind as to help with beta testing this? Could you please add the following to your pubspec and let me know what works and what doesn't? 

```
dependency_overrides:
  datadog_flutter:
    git: 
      url: git@github.com:greenbits/datadog_flutter.git
      ref: add-web-support
```

**Comment by tshedor** [comment]
Hey @acherifi I'm going to merge this; let me know if you encounter bugs

**Comment by acherifi** [comment]
Sorry I've been away lately! I will gladly test this!
