### ISSUE TITLE
Unable to send log (Android)

### ISSUE THREAD

**Issue by rupas385** [greenbits/datadog_flutter#49]
Hi,

I am trying to connect my flutter app with datadog using this package. On iOS work fine, but on Android can't connect to datadog. No send logs and RUM not work, nothing happens.

Init datadog:

```java
await DatadogFlutter.initialize(
     clientToken: token,
     serviceName: "MyApp - ${GeneralPlatform.isAndroid ? "Android" : "iOS"}",
     environment: Env.environment.currentMode.toString(),
     trackingConsent: TrackingConsent.granted,
     androidRumApplicationId: "MY ANDROID RUM ID",
     iosRumApplicationId: "MY IOS RUM ID",
     flavorName: Env.environment.currentMode.toString(),
     useEUEndpoints: true
   );
```

Send log:

```java
DatadogLogger().log("TEST LOG", Level.SEVERE);
```

The only error I see in logcat is this:

```
W/OkHttp  (28387): unable to load android socket classes
W/OkHttp  (28387): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (28387): 	at java.lang.Class.getMethod(Class.java:2072)
W/OkHttp  (28387): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
W/OkHttp  (28387): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (28387): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (28387): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (28387): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (28387): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (28387): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (28387): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (28387): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (28387): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (28387): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (28387): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W/OkHttp  (28387): 	at com.datadog.android.core.internal.CoreFeature.<clinit>(CoreFeature.kt:72)
W/OkHttp  (28387): 	at com.datadog.android.Datadog.setUserInfo(Datadog.kt:293)
W/OkHttp  (28387): 	at com.greenbits.datadog_flutter.DatadogFlutterPlugin.onMethodCall(DatadogFlutterPlugin.kt:212)
W/OkHttp  (28387): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/OkHttp  (28387): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/OkHttp  (28387): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/OkHttp  (28387): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/OkHttp  (28387): 	at android.os.MessageQueue.next(MessageQueue.java:339)
W/OkHttp  (28387): 	at android.os.Looper.loop(Looper.java:199)
W/OkHttp  (28387): 	at android.app.ActivityThread.main(ActivityThread.java:8258)
W/OkHttp  (28387): 	at java.lang.reflect.Method.invoke(Native Method)
W/OkHttp  (28387): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
W/OkHttp  (28387): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

Also I verified that I have Internet Permission in my manifest.

**Comment by tshedor** [comment]
Hi @rupas385 thanks for using datadog flutter. Are you able to make any HTTP requests with your Flutter app?

**Comment by tshedor** [comment]
Hey @rupas385 I'm going to close this out due to inactivity.
